server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usersdb
    username: root
    password: 123456

logging:
  level:
    web: trace
    org:
      springframework:
        security: debug
        web: trace

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma Powerup"
appVersion: "1.0.0"
